name: Build Docker Image

on:
  push:
    branches:
      - main  # or your default branch
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Docker tag with datetime
        id: vars
        run: echo "TAG=$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_ENV
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: jpablodrexler/ai-chatbot:${{ env.TAG }}
      
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Deploy Docker container to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ai-chatbot-grupo66
          images: docker.io/jpablodrexler/ai-chatbot:${{ env.TAG }}
